# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Sky Well Test Project' do
	pod 'Alamofire', ‘= 3.0’
	pod 'ImageLoader', ‘= 0.9.0’
end

